#pragma checksum "..\..\MainWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "59F731BD4466291E9CBB0A9427BFE274350DA82CE2726FADB10633233B2ED021"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Morta;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Morta {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem ClearFields;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem CloseProgram;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem report_Menu_Btn;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem docGen_Menu;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem DescriptionTab;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock propertyTitleTextBlock;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox propertyTitle;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock propertyDescriptionTextBlock;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PropertyDescription;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmTitle;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmDescription;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem DetailsTab;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox firstLineAddress;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox postCode;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox city;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmAddress;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox furnished;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox unfurnished;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmFurnishState;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton gasHeating;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton electricHeating;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmHeatingState;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox hmoLicence;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmHmoState;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DateAvailablePick;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ConfirmDate;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem RatingsTab;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox taxBands;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmTaxBand;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox energyRatings;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmEnergyRating;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem PricingTab;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock rentValueTextblock;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox rentValue;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmRentValue;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock depositValueTextBlock;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox depositValue;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmDepositValue;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem LandlordTab;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock landlordRegTextBlock;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox landlordRegNumTextField;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmLandlordRegNum;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock landlordNameTextBlock;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox landlordNameTextField;
        
        #line default
        #line hidden
        
        
        #line 147 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmLandlordName;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock landlordTelNumTextBlock;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox landlordTelNumTextField;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox confirmLandlordTelNum;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem ImagesTab;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpen;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPath;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ImagePreview;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox imgCounterText;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem PreviewTab;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PreviewProperty;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button submitBtn;
        
        #line default
        #line hidden
        
        
        #line 182 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PreviewProp;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Morta;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ClearFields = ((System.Windows.Controls.MenuItem)(target));
            
            #line 13 "..\..\MainWindow.xaml"
            this.ClearFields.Click += new System.Windows.RoutedEventHandler(this.ClearFieldsClick);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CloseProgram = ((System.Windows.Controls.MenuItem)(target));
            
            #line 14 "..\..\MainWindow.xaml"
            this.CloseProgram.Click += new System.Windows.RoutedEventHandler(this.CloseProgram_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.report_Menu_Btn = ((System.Windows.Controls.MenuItem)(target));
            
            #line 16 "..\..\MainWindow.xaml"
            this.report_Menu_Btn.Click += new System.Windows.RoutedEventHandler(this.ReportBtn_Menu_click);
            
            #line default
            #line hidden
            
            #line 16 "..\..\MainWindow.xaml"
            this.report_Menu_Btn.ToolTipOpening += new System.Windows.Controls.ToolTipEventHandler(this.SetTooltipReport);
            
            #line default
            #line hidden
            return;
            case 4:
            this.docGen_Menu = ((System.Windows.Controls.MenuItem)(target));
            
            #line 17 "..\..\MainWindow.xaml"
            this.docGen_Menu.Click += new System.Windows.RoutedEventHandler(this.DocGen_Menu_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 18 "..\..\MainWindow.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.Help_MenuItem_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DescriptionTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 7:
            this.propertyTitleTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.propertyTitle = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.propertyDescriptionTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.PropertyDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.confirmTitle = ((System.Windows.Controls.CheckBox)(target));
            
            #line 32 "..\..\MainWindow.xaml"
            this.confirmTitle.Checked += new System.Windows.RoutedEventHandler(this.ConfirmTitle_Checked);
            
            #line default
            #line hidden
            return;
            case 12:
            this.confirmDescription = ((System.Windows.Controls.CheckBox)(target));
            
            #line 33 "..\..\MainWindow.xaml"
            this.confirmDescription.Checked += new System.Windows.RoutedEventHandler(this.ConfirmDescription_Checked);
            
            #line default
            #line hidden
            return;
            case 13:
            this.DetailsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 14:
            this.firstLineAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.postCode = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.city = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.confirmAddress = ((System.Windows.Controls.CheckBox)(target));
            
            #line 52 "..\..\MainWindow.xaml"
            this.confirmAddress.Checked += new System.Windows.RoutedEventHandler(this.ConfirmAddress_Checked);
            
            #line default
            #line hidden
            return;
            case 18:
            this.furnished = ((System.Windows.Controls.CheckBox)(target));
            
            #line 56 "..\..\MainWindow.xaml"
            this.furnished.Checked += new System.Windows.RoutedEventHandler(this.Furnished_Checked);
            
            #line default
            #line hidden
            return;
            case 19:
            this.unfurnished = ((System.Windows.Controls.CheckBox)(target));
            
            #line 57 "..\..\MainWindow.xaml"
            this.unfurnished.Checked += new System.Windows.RoutedEventHandler(this.Unfurnished_Checked);
            
            #line default
            #line hidden
            return;
            case 20:
            this.confirmFurnishState = ((System.Windows.Controls.CheckBox)(target));
            
            #line 58 "..\..\MainWindow.xaml"
            this.confirmFurnishState.Checked += new System.Windows.RoutedEventHandler(this.ConfirmFurnishState_Checked);
            
            #line default
            #line hidden
            return;
            case 21:
            this.gasHeating = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 22:
            this.electricHeating = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 23:
            this.confirmHeatingState = ((System.Windows.Controls.CheckBox)(target));
            
            #line 64 "..\..\MainWindow.xaml"
            this.confirmHeatingState.Checked += new System.Windows.RoutedEventHandler(this.ConfirmHeatingState_Checked);
            
            #line default
            #line hidden
            return;
            case 24:
            this.hmoLicence = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.confirmHmoState = ((System.Windows.Controls.CheckBox)(target));
            
            #line 69 "..\..\MainWindow.xaml"
            this.confirmHmoState.Checked += new System.Windows.RoutedEventHandler(this.ConfirmHmoState_Checked);
            
            #line default
            #line hidden
            return;
            case 26:
            this.DateAvailablePick = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 27:
            this.ConfirmDate = ((System.Windows.Controls.CheckBox)(target));
            
            #line 72 "..\..\MainWindow.xaml"
            this.ConfirmDate.Checked += new System.Windows.RoutedEventHandler(this.ConfirmDate_Checked);
            
            #line default
            #line hidden
            return;
            case 28:
            this.RatingsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 29:
            this.taxBands = ((System.Windows.Controls.ListBox)(target));
            return;
            case 30:
            this.confirmTaxBand = ((System.Windows.Controls.CheckBox)(target));
            
            #line 101 "..\..\MainWindow.xaml"
            this.confirmTaxBand.Checked += new System.Windows.RoutedEventHandler(this.ConfirmTaxBand_Checked);
            
            #line default
            #line hidden
            return;
            case 31:
            this.energyRatings = ((System.Windows.Controls.ListBox)(target));
            return;
            case 32:
            this.confirmEnergyRating = ((System.Windows.Controls.CheckBox)(target));
            
            #line 113 "..\..\MainWindow.xaml"
            this.confirmEnergyRating.Checked += new System.Windows.RoutedEventHandler(this.ConfirmEnergyRating_Checked);
            
            #line default
            #line hidden
            return;
            case 33:
            this.PricingTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 34:
            this.rentValueTextblock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.rentValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 36:
            this.confirmRentValue = ((System.Windows.Controls.CheckBox)(target));
            
            #line 125 "..\..\MainWindow.xaml"
            this.confirmRentValue.Checked += new System.Windows.RoutedEventHandler(this.ConfirmRentValue_Checked);
            
            #line default
            #line hidden
            return;
            case 37:
            this.depositValueTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 38:
            this.depositValue = ((System.Windows.Controls.TextBox)(target));
            return;
            case 39:
            this.confirmDepositValue = ((System.Windows.Controls.CheckBox)(target));
            
            #line 131 "..\..\MainWindow.xaml"
            this.confirmDepositValue.Checked += new System.Windows.RoutedEventHandler(this.ConfirmDepositValue_Checked);
            
            #line default
            #line hidden
            return;
            case 40:
            this.LandlordTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 41:
            this.landlordRegTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.landlordRegNumTextField = ((System.Windows.Controls.TextBox)(target));
            return;
            case 43:
            this.confirmLandlordRegNum = ((System.Windows.Controls.CheckBox)(target));
            
            #line 142 "..\..\MainWindow.xaml"
            this.confirmLandlordRegNum.Checked += new System.Windows.RoutedEventHandler(this.ConfirmLandlordRegNum_Checked);
            
            #line default
            #line hidden
            return;
            case 44:
            this.landlordNameTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.landlordNameTextField = ((System.Windows.Controls.TextBox)(target));
            return;
            case 46:
            this.confirmLandlordName = ((System.Windows.Controls.CheckBox)(target));
            
            #line 147 "..\..\MainWindow.xaml"
            this.confirmLandlordName.Checked += new System.Windows.RoutedEventHandler(this.ConfirmLandlordName_Checked);
            
            #line default
            #line hidden
            return;
            case 47:
            this.landlordTelNumTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 48:
            this.landlordTelNumTextField = ((System.Windows.Controls.TextBox)(target));
            return;
            case 49:
            this.confirmLandlordTelNum = ((System.Windows.Controls.CheckBox)(target));
            
            #line 152 "..\..\MainWindow.xaml"
            this.confirmLandlordTelNum.Checked += new System.Windows.RoutedEventHandler(this.ConfirmLandlordTelNum_Checked);
            
            #line default
            #line hidden
            return;
            case 50:
            this.ImagesTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 51:
            this.btnOpen = ((System.Windows.Controls.Button)(target));
            
            #line 162 "..\..\MainWindow.xaml"
            this.btnOpen.Click += new System.Windows.RoutedEventHandler(this.Image_load_BtnOpen_Click);
            
            #line default
            #line hidden
            return;
            case 52:
            this.txtPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 53:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 165 "..\..\MainWindow.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.Image_Save_BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 54:
            this.ImagePreview = ((System.Windows.Controls.Image)(target));
            return;
            case 55:
            this.imgCounterText = ((System.Windows.Controls.TextBox)(target));
            return;
            case 56:
            this.PreviewTab = ((System.Windows.Controls.TabItem)(target));
            
            #line 176 "..\..\MainWindow.xaml"
            this.PreviewTab.GotFocus += new System.Windows.RoutedEventHandler(this.PreviewTab_GotFocus);
            
            #line default
            #line hidden
            return;
            case 57:
            this.PreviewProperty = ((System.Windows.Controls.Button)(target));
            return;
            case 58:
            this.submitBtn = ((System.Windows.Controls.Button)(target));
            
            #line 179 "..\..\MainWindow.xaml"
            this.submitBtn.Click += new System.Windows.RoutedEventHandler(this.SubmitBtn_Click);
            
            #line default
            #line hidden
            return;
            case 59:
            this.PreviewProp = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

